env:
  browser: true
  node: true
  es2021: true
  jquery: true
extends:
  - standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  comma-dangle:
    - error
    - always-multiline
  padded-blocks: off
ignorePatterns: '*.min.js'
